version: "3.9"

services:
  pg-dev:
    image: postgres:16
    container_name: pg-server-dev
    profiles: ["pg-dev"]
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pg_dev_data:/var/lib/postgresql/data
    networks:
      - adopet-net
  
  pg-prod:
    image: postgres:16
    container_name: pg-server-prod
    profiles: ["pg-prod"]
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pg_prod_data:/var/lib/postgresql/data
    networks:
      - adopet-net

  mariadb-dev:
    image: mariadb:11
    container_name: mariadb-server-dev
    profiles: ["mariadb-dev"]
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_dev_data:/var/lib/mysql
    networks:
      - adopet-net
  
  mariadb-prod:
    image: mariadb:11
    container_name: mariadb-server-prod
    profiles: ["mariadb-prod"]
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_prod_data:/var/lib/mysql
    networks:
      - adopet-net

networks:
  adopet-net:
    name: adopet-net
    external: true

volumes:
  pg_dev_data:
  pg_prod_data:
  mariadb_dev_data:
  mariadb_prod_data: